module.exports = function (app) {
  var express = require("express");
  var router = express.Router();
  let FTAccounts = require("../services/fund.accounts.services");

  router.get("/getTransfer", async (req, res) => {
    let response = await FTAccounts.getTransfers(req);
    res.send(response);
  });

  router.get("/getAllTransfers", async (req, res) => {
    let response = await FTAccounts.getAllTransferss(req);
    res.send(response);
  });

  router.post("/addTransfer", async (req, res) => {
    let response = await FTAccounts.addFTTransfers(req);
    res.send(response);
  });

  router.put("/editTransfer", async (req, res) => {
    let response = await FTAccounts.editFTTransfer(req);
    res.send(response);
  });

  router.post("/deleteTransfer", async (req, res) => {
    let response = await FTAccounts.deleteFTTransfer(req);
    res.send(response);
  });

  router.get("/getMenus", async (req, res) => {
    res.send({
      text: "My Response Text",
      body: [
        {
          title: "Dashboard",
          icon: "FaHome",
          data: [
            {
              accountNumber: "1234567889",
              title: "User Dashboard",
              id: 1,
              icon: "FaChart",
            },
          ],
        },
        {
          title: "Balance and Transaction",
        },
        {
          title: "Instruments",
          name: "Sadfwfw",
        },
        {
          title: "Beneficiary",
          data: [
            {
              title: "Add Bill Benificiary (From File)",
              icon: "icon-home",
              id: 8,
            },
            {
              title: "Add Bill Beneficiary (Manual)",
              icon: "icon-home",
              id: 9,
            },
            {
              title: "Add General Benificiary (From File)",
              icon: "icon-home",
              id: 10,
            },
            {
              title: "Add General Benificiary (Manual)",
              icon: "icon-home",
              id: 11,
            },
            {
              title: "Add Salary Benificiary (Manual)",
              icon: "icon-home",
              id: 12,
            },
            {
              title: "Add Salary Benificiary (From File)",
              icon: "icon-home",
              id: 13,
            },
            { title: "Benificiary category", icon: "icon-home", id: 14 },
            { title: " View Benificiary ", icon: "icon-home", id: 15 },
            { title: "View Bill Benificiary ", icon: "icon-home", id: 16 },
          ],
        },
        {
          title: "Payments",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            { title: "General Payment (Manual)", icon: "icon-home", id: 17 },

            {
              title: "Salary Payment (Manual)",
              icon: "icon-home",
              id: 20,
            },
            {
              title: "Bill Payment (Manual)",
              icon: "icon-home",
              id: 21,
            },
            { title: "Adhoc Payments", icon: "icon-home", id: 235 },
            { title: "RTGS Pay", icon: "icon-home", id: 236 },
          ],
        },

        {
          title: "Transaction",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              title: "Transaction History",
              icon: "icon-home",
              id: 88,
            },
            {
              title: "Transmit Transactions",
              icon: "icon-home",
              id: 90,
            },
            {
              title: "Approve/Reject Transactions",
              icon: "icon-home",
              id: 89,
            },
          ],
        },
        { title: "Check Requests", name: "Sadfwfw", data: [] },
        {
          title: "User Management",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [],
        },
        { title: "Broadcast Messages", name: "Sadfwfw", data: [] },
        { title: "Others", name: "Sadfwfw", data: [] },
      ],
    });
  });

  router.post("/fetchAccountGET", async (req, res) => {
    res.send({
      text: "My Response Text",
      body: [
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
              id: 1,
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              id: 2,
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              id: 3,
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              id: 4,
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              id: 5,
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },

        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 4",
          name: "Sadfwfw",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 4",
          name: "Sadfwfw",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 3",
          name: "Sadfwfw",
          wegwe: "icon-home",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
              wegwe: "icon-home",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 4",
          name: "Sadfwfw",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
        {
          title: "Account 453",
          name: "Sadfwfw",
          data: [
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
            {
              accountNumber: "1234567889",
              acT: "ABVD",
            },
          ],
        },
      ],
    });
  });
  router.post("/login", async (req, res) => {
    res.send({
      code: 1,
      message: "User logged in successfully",
      content: {
        projects: [],
        roles: [
          {
            permissions: [
              {
                roles: [],
                _id: "60f58a51781474576a80514b",
                name: "CreateProject",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bdecb72cfae3b7a554b3d",
                name: "PreviewTrigger",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611be23a72cfae3b7a554b43",
                name: "CreateTrigger",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faaf8a781474576a805195",
                name: "Components",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "60faaf8e781474576a805196",
                name: "Widgets",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faaf9a781474576a805198",
                name: "Screens",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611be9de72cfae3b7a554b4e",
                name: "ViewTriggerDocumentation",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "60faaf93781474576a805197",
                name: "Ribbon",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faafa0781474576a805199",
                name: "Assets",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faaf8e781474576a805196",
                name: "Widgets",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611be00a72cfae3b7a554b3e",
                name: "ViewTrigger",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611be89272cfae3b7a554b4a",
                name: "PreviewWidget",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.preview",
                localeTooltip: "actions.tooltip.preview",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faafaf781474576a80519b",
                name: "Theme",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611be93172cfae3b7a554b4c",
                name: "ViewWidgetDocumentation",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611be93b72cfae3b7a554b4d",
                name: "AddWidgetDocumentation",
                type: "ACTION",
                iconName: "FaFileSignature",
                localeLabel: "actions.label.add",
                localeTooltip: "actions.tooltip.add",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611bed8a72cfae3b7a554b50",
                name: "CreateComponent",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.tooltip.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611ae172cf8fbad0777ae282",
                name: "CreateWidget",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bca81a3d3cdbe598d48d7",
                name: "AddScreen",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611beeb372cfae3b7a554b51",
                name: "ViewScreenDocumentation",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611bef1b72cfae3b7a554b52",
                name: "AddScreenDocumentation",
                type: "ACTION",
                iconName: "FaFileSignature",
                localeLabel: "actions.label.add",
                localeTooltip: "actions.tooltip.add",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611bca65a3d3cdbe598d48d6",
                name: "EditScreen",
                type: "ACTION",
                iconName: "FaEdit",
                localeLabel: "actions.label.edit",
                localeTooltip: "actions.tooltip.edit",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611ae180cf8fbad0777ae283",
                name: "CreateScreen",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "tactions.ooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611ae195cf8fbad0777ae284",
                name: "AddAsset",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bc4b4a3d3cdbe598d48d4",
                name: "SaveProject",
                type: "ACTION",
                iconName: "FaDownload",
                localeLabel: "ribbonMenu.save",
                localeTooltip: "ribbonMenu.save",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bea2772cfae3b7a554b4f",
                name: "AddTriggerDocumentation",
                type: "ACTION",
                iconName: "FaFileSignature",
                localeLabel: "actions.label.add",
                localeTooltip: "actions.tooltip.add",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "611bbc23a3d3cdbe598d48cf",
                name: "Triggers",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bbc3aa3d3cdbe598d48d0",
                name: "AddTrigger",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bbc46a3d3cdbe598d48d1",
                name: "EditTrigger",
                type: "ACTION",
                iconName: "FaEdit",
                localeLabel: "actions.label.edit",
                localeTooltip: "actions.tooltip.edit",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611be8f872cfae3b7a554b4b",
                name: "EditWidget",
                type: "ACTION",
                iconName: "FaEdit",
                localeLabel: "actions.label.edit",
                localeTooltip: "actions.tooltip.edit",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bba35a3d3cdbe598d48ce",
                name: "Canvas",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "6124f0ce394dd31c324dfa47",
                name: "AddComponentDocumentation",
                type: "ACTION",
                iconName: "FaFileSignature",
                localeLabel: "actions.label.add",
                localeTooltip: "actions.tooltip.add",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "6124f0a3394dd31c324dfa46",
                name: "ViewComponentDocumentation",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bc4a6a3d3cdbe598d48d3",
                name: "PreviewProject",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                localeLabel: "projects.label.preview",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "614312ddf6f22e169283290e",
                name: "EditProjectConfiguration",
                type: "ACTION",
                iconName: "FaEdit",
                localeLabel: "actions.label.editconfiguration",
                localeTooltip: "actions.tooltip.editconfiguration",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "611bbc89a3d3cdbe598d48d2",
                name: "DeleteTrigger",
                type: "ACTION",
                iconName: "FaTrash",
                localeLabel: "actions.label.delete",
                localeTooltip: "actions.tooltip.delete",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faaf8a781474576a805195",
                name: "Components",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
              {
                roles: [],
                _id: "61437a37d6adb765f8006ca3",
                name: "DeleteWidget",
                type: "ACTION",
                iconName: "FaTrash",
                localeLabel: "actions.label.delete",
                localeTooltip: "actions.tooltip.delete",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "61437a41d6adb765f8006ca4",
                name: "DeleteScreen",
                type: "ACTION",
                iconName: "FaTrash",
                localeLabel: "actions.label.delete",
                localeTooltip: "actions.tooltip.delete",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "61437e14d6adb765f8006ca5",
                name: "DeleteProject",
                type: "ACTION",
                iconName: "FaTrash",
                localeLabel: "actions.label.delete",
                localeTooltip: "actions.tooltip.delete",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "61b0749526ab1f2544e05fda",
                name: "PublishProject",
                type: "ACTION",
                iconName: "FaUpload",
                localeLabel: "projects.publish.title",
                localeTooltip: "projects.publish.title",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "61b8418cfe0dd3149407784f",
                name: "DownloadJSON",
                type: "ACTION",
                iconName: "FaDownload",
                localeLabel: "projects.downloadJSON",
                localeTooltip: "projects.downloadJSON",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
            ],
            _id: "60f58a6c781474576a80514e",
            name: "Admin",
            status: "ACTIVE",
          },
          {
            permissions: [
              {
                roles: [],
                _id: "60faafa9781474576a80519a",
                name: "OpenProject",
                type: "ACTION",
                iconName: "FaEdit",
                localeLabel: "actions.label.open",
                localeTooltip: "actions.tooltip.open",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "ACTIVE",
              },
              {
                roles: [],
                _id: "60faafaf781474576a80519b",
                name: "Theme",
                type: "ACTION",
                iconName: "FaFileAlt",
                localeLabel: "actions.label.view",
                localeTooltip: "actions.tooltip.view",
                updatedAt: "2021-08-25T14:12:12.764Z",
                iconColor: "#1c2b5a",
                status: "INACTIVE",
              },
            ],
            _id: "60fab08d781474576a80519e",
            name: "User",
            status: "ACTIVE",
          },
        ],
        _id: "60f589a4ee7ad31dc2c38f47",
        name: "haseeb",
        username: "haseeb",
        __v: 4743,
        lastLoginTime: "2022-02-07T06:28:59.972Z",
        sessionAuthorized: true,
        gender: "male",
        status: "active",
        email: "haseeb.ahmed@avanzasolutions.com",
        createdAt: "2021-07-30T21:59:29.539Z",
        lastLogoutTime: "2022-01-19T06:59:12.526Z",
        updatedAt: "2022-02-07T06:28:59.983Z",
        lastSessionDuration: "00:17:48",
        Permission: [],
        sessionId: 1644215339974,
        TET: 30000,
        refreshToken:
          "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imhhc2VlYiIsImV4cGlyZSI6MTg4NDIyMTczMDYyM30.k9kG4Io1D98HQBqJqmZjQd8x0l_tBkFu_F1dw5fPSK4",
        refreshTET: 60000,
        token:
          "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Imhhc2VlYiIsImV4cGlyZSI6MTc2NDIyMTczMDYyM30.378ughHiK-1HKT6WDNJahryx4ALz6pKWXIFSV8wcwbA",
        permissions: [
          {
            roles: [],
            _id: "60f58a51781474576a80514b",
            name: "CreateProject",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bdecb72cfae3b7a554b3d",
            name: "PreviewTrigger",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611be23a72cfae3b7a554b43",
            name: "CreateTrigger",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "60faaf8e781474576a805196",
            name: "Widgets",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "60faaf9a781474576a805198",
            name: "Screens",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "60faaf93781474576a805197",
            name: "Ribbon",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "60faafa0781474576a805199",
            name: "Assets",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611be00a72cfae3b7a554b3e",
            name: "ViewTrigger",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611be89272cfae3b7a554b4a",
            name: "PreviewWidget",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.preview",
            localeTooltip: "actions.tooltip.preview",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bed8a72cfae3b7a554b50",
            name: "CreateComponent",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.tooltip.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611ae172cf8fbad0777ae282",
            name: "CreateWidget",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bca81a3d3cdbe598d48d7",
            name: "AddScreen",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bca65a3d3cdbe598d48d6",
            name: "EditScreen",
            type: "ACTION",
            iconName: "FaEdit",
            localeLabel: "actions.label.edit",
            localeTooltip: "actions.tooltip.edit",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611ae180cf8fbad0777ae283",
            name: "CreateScreen",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "tactions.ooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611ae195cf8fbad0777ae284",
            name: "AddAsset",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bc4b4a3d3cdbe598d48d4",
            name: "SaveProject",
            type: "ACTION",
            iconName: "FaDownload",
            localeLabel: "ribbonMenu.save",
            localeTooltip: "ribbonMenu.save",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bbc23a3d3cdbe598d48cf",
            name: "Triggers",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bbc3aa3d3cdbe598d48d0",
            name: "AddTrigger",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bbc46a3d3cdbe598d48d1",
            name: "EditTrigger",
            type: "ACTION",
            iconName: "FaEdit",
            localeLabel: "actions.label.edit",
            localeTooltip: "actions.tooltip.edit",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611be8f872cfae3b7a554b4b",
            name: "EditWidget",
            type: "ACTION",
            iconName: "FaEdit",
            localeLabel: "actions.label.edit",
            localeTooltip: "actions.tooltip.edit",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bba35a3d3cdbe598d48ce",
            name: "Canvas",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "6124f0ce394dd31c324dfa47",
            name: "AddComponentDocumentation",
            type: "ACTION",
            iconName: "FaFileSignature",
            localeLabel: "actions.label.add",
            localeTooltip: "actions.tooltip.add",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "6124f0a3394dd31c324dfa46",
            name: "ViewComponentDocumentation",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeLabel: "actions.label.view",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bc4a6a3d3cdbe598d48d3",
            name: "PreviewProject",
            type: "ACTION",
            iconName: "FaFileAlt",
            localeTooltip: "actions.tooltip.view",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            localeLabel: "projects.label.preview",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "614312ddf6f22e169283290e",
            name: "EditProjectConfiguration",
            type: "ACTION",
            iconName: "FaEdit",
            localeLabel: "actions.label.editconfiguration",
            localeTooltip: "actions.tooltip.editconfiguration",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "611bbc89a3d3cdbe598d48d2",
            name: "DeleteTrigger",
            type: "ACTION",
            iconName: "FaTrash",
            localeLabel: "actions.label.delete",
            localeTooltip: "actions.tooltip.delete",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "61437a37d6adb765f8006ca3",
            name: "DeleteWidget",
            type: "ACTION",
            iconName: "FaTrash",
            localeLabel: "actions.label.delete",
            localeTooltip: "actions.tooltip.delete",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "61437a41d6adb765f8006ca4",
            name: "DeleteScreen",
            type: "ACTION",
            iconName: "FaTrash",
            localeLabel: "actions.label.delete",
            localeTooltip: "actions.tooltip.delete",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "61437e14d6adb765f8006ca5",
            name: "DeleteProject",
            type: "ACTION",
            iconName: "FaTrash",
            localeLabel: "actions.label.delete",
            localeTooltip: "actions.tooltip.delete",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "61b0749526ab1f2544e05fda",
            name: "PublishProject",
            type: "ACTION",
            iconName: "FaUpload",
            localeLabel: "projects.publish.title",
            localeTooltip: "projects.publish.title",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "61b8418cfe0dd3149407784f",
            name: "DownloadJSON",
            type: "ACTION",
            iconName: "FaDownload",
            localeLabel: "projects.downloadJSON",
            localeTooltip: "projects.downloadJSON",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
          {
            roles: [],
            _id: "60faafa9781474576a80519a",
            name: "OpenProject",
            type: "ACTION",
            iconName: "FaEdit",
            localeLabel: "actions.label.open",
            localeTooltip: "actions.tooltip.open",
            updatedAt: "2021-08-25T14:12:12.764Z",
            iconColor: "#1c2b5a",
            status: "ACTIVE",
          },
        ],
      },
    });
  });

  router.get("/getCards", async (req, res) => {
    res.send({
      data: [
        {
          instrumentNumber: "9988123114421",
          instrumentTitle: "VISA",
          currency: "USD",
        },
        {
          instrumentNumber: "00442122444211",
          instrumentTitle: "MASTER",
          currency: "USD",
        },
        {
          instrumentNumber: "4429102030201",
          instrumentTitle: "UNION",
          currency: "USD",
        },
        {
          instrumentNumber: "09099400012321",
          instrumentTitle: "American express",
          currency: "USD",
        },
        {
          instrumentNumber: "224400992",
          instrumentTitle: "American express 2",
          currency: "USD",
        },
      ],
    });
  });

  app.use("/FT", router);
};
